# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeSync' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafeSync
pod 'IBAnimatable'
pod "KRProgressHUD"
end

#target 'SafeSync Watch' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for SafeSync
#  pod 'Firebase/Database'
#  pod 'Firebase/Crashlytics'
#  pod 'Firebase/Messaging'
#end
